// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SharklineTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void lOGINCONTAINSEMAIL() {
    driver.get("http://localhost:8080/sharkline/");
    {
      List<WebElement> elements = driver.findElements(By.id("email"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.cssSelector("form")).getText(), is("Please enter your email in the field. This is the email you use to log into the system.\\\\nEmail Address:\\\\n\\\\nPlease enter the password you used to create your account. If you forget what your password is, please click the \\\"Forgot Password\\\" button below.\\\\nPassword:"));
  }
  @Test
  public void lOGINCONTAINSHELPBUTTON() {
    driver.get("http://localhost:8080/sharkline/");
    driver.findElement(By.id("emailhelp")).click();
    {
      List<WebElement> elements = driver.findElements(By.id("emailhelp"));
      assert(elements.size() == 0);
    }
    driver.findElement(By.id("passwordhelp")).click();
    driver.findElement(By.id("passwordhelp")).click();
    driver.findElement(By.id("passwordhelp")).click();
    {
      List<WebElement> elements = driver.findElements(By.id("passwordhelp"));
      assert(elements.size() == 0);
    }
    driver.findElement(By.cssSelector("form")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("button:nth-child(2)"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector("button:nth-child(2)")).click();
    driver.findElement(By.id("emailhelp")).click();
    {
      List<WebElement> elements = driver.findElements(By.id("emailhelp"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.id("passwordhelp")).click();
    {
      List<WebElement> elements = driver.findElements(By.id("passwordhelp"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void lOGINCONTAINSPASSWORD() {
    driver.get("http://localhost:8080/sharkline/");
    assertThat(driver.findElement(By.cssSelector("form")).getText(), is("Please enter your email in the field. This is the email you use to log into the system.\\\\nEmail Address:\\\\n\\\\nPlease enter the password you used to create your account. If you forget what your password is, please click the \\\"Forgot Password\\\" button below.\\\\nPassword:"));
    {
      List<WebElement> elements = driver.findElements(By.id("password"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void lOGINFORGOTPASSWORDPRESENT() {
    driver.get("http://localhost:8080/sharkline/");
    {
      List<WebElement> elements = driver.findElements(By.id("forgot"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.id("forgot")).click();
    assertThat(driver.getTitle(), is("Forgot password?"));
  }
  @Test
  public void lOGINSUCCESFULBUSINESS() {
    driver.get("http://localhost:8080/sharkline/");
    driver.findElement(By.id("email")).sendKeys("amazonHQ@gmail.com");
    driver.findElement(By.id("password")).sendKeys("bezos420");
    driver.findElement(By.cssSelector(".signin_button")).click();
    assertThat(driver.getTitle(), is("SharkLine - Jeff Bezos"));
  }
  @Test
  public void lOGINSUCCESSFULINVESTOR() {
    driver.get("http://localhost:8080/sharkline/");
    driver.findElement(By.id("email")).sendKeys("johnsmith@gmail.com");
    driver.findElement(By.id("password")).sendKeys("yankees1990");
    driver.findElement(By.cssSelector(".signin_button")).click();
    assertThat(driver.getTitle(), is("SharkLine - John Smith"));
  }
}
